ingress:
  main:
    enabled: true

    className: traefik

    hosts:
      - host: syncthing.lan
        paths:
          - path: /
            pathType: Prefix

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 10Gi
